### ISSUE TITLE
neovide chinese input wrong

### ISSUE THREAD

**Issue by notfornothing** [TENX-S/VimTips#1]
哥哥，能告诉我你用的哪个版本吗？我用neovide 0.5.0 版本才中文显示才不会乱码，但是输入会变成这种样式

![image](https://user-images.githubusercontent.com/43561526/121809190-6d883f00-cc8e-11eb-994e-6949d5cb4dfd.png)

**Comment by andrew-ares** [comment]
0.4.4
那啥，你是不是问错地方了

**Comment by notfornothing** [comment]
你现在解决了中文输入问题了吗？
❤️❤️❤️

**Comment by andrew-ares** [comment]
原来你说 neovide ，当时我用的时候就有中文输入法的问题，我记得有人提了一个 issue 不过没解决，后来我就没用 neovide 了，你可以尝试从最新的 master 分支编译一下试试

**Comment by notfornothing** [comment]
好，
我通过issue找到你的。谢谢你！❤️
